# 블로그 실제 도메인 주소 (kyt323-tech로 설정)
url: 'https://kyt323-tech.github.io'

# 블로그 타이틀 및 설명
title: 'kyt323-tech의 기술 블로그'
tagline: '주제별 글을 모아두는 나만의 공간'

# 작성자 및 타임존 설정
author: 'kyt323-tech'
timezone: 'Asia/Seoul'
lang: 'ko-KR'
